### ISSUE TITLE
Todo app doesn't build.

### ISSUE THREAD

**Issue by FieldMarshallVague** [skclusive/Skclusive.Blazor.Samples#12]
Fresh folder, clone repo from Master or Dev.  Get errors about 'not suitable method to override'.  I've looked through code in both branches to see if there is a version I should be using, but can't see the 'DisposeAsync' anywhere on TodoAppComponent.

I copied the dependency projects locally, instead of using packages (to change version) and this doesn't work, so it looks like there is a mismatch with the checked in code and your code locally.

If you can provide the correct steps to get the Todo app running, that would be great.

**Comment by skclusive** [comment]
oh will check and updated. thanks for reporting.

**Comment by skclusive** [comment]
able to build Todo samples in master branch without modification.

 if you are using dependency projects, please switch to develop branch on dependency project. also .NET 5.0.0 rc2 required.

**Comment by FieldMarshallVague** [comment]
Hmm, that's odd.  I am using Rc2 and tried to build the samples (which failed) before I tried referencing the dependencies as projects.  I'll give it another go.

**Comment by FieldMarshallVague** [comment]
you should know, that I get this error when cloning.

![image](https://user-images.githubusercontent.com/2116744/98537708-91f7e500-2281-11eb-8593-f5e7d7ecba6f.png)

I tried many times to clone, but ended up using the download link instead.

**Comment by FieldMarshallVague** [comment]
Just giving you process feedback...  I download the repo as a ZIP and unpack in new folder.  I try build and it errors, saying the projects dependencies don't exist.

![image](https://user-images.githubusercontent.com/2116744/98541163-e6519380-2286-11eb-95c6-e8b4afaa2bd4.png)

This is understandable, so I clone the repos into the relative folders.  So it looks like this:

![image](https://user-images.githubusercontent.com/2116744/98541336-2ca6f280-2287-11eb-8ab0-22205b0f6b81.png)

But the build still fails because it can't ind the project files.  This is due to them being in a sub-folder of 'src'.

e.g.  C:\projects\blazor\skclusive\Skclusive.Mobx.Component\src\Component (note the last 'component').

So, I edit the csproj file to add these missing folders.  Rebuilding gives and error saying the project information cannot be found, so I do a dotnet restore from CLI.  Then I build each dep project separately.  

DomHelpers and DevTools result in error: 

`
The command "npm run build" exited with code 1.
`

But the DLLs are created anyway, so I retry the build of TodoApp.Client.  This proceeds further than last time, but I get the error:

`
'TodoAppComponent.DisposeAsync()': no suitable method found to override	TodoApp.Client	C:\projects\blazor\skclusive\Skclusive.Blazor.Samples-master\Skclusive.Blazor.TodoApp\TodoApp.Client\Components\App\TodoApp.cs
`

So, perhaps something in the NPM build step is causing this?  Any suggestions?

**Comment by skclusive** [comment]
thanks for the details. will follow the above steps and try to reproduce.

**Comment by skclusive** [comment]
reproduced. sorry. i should not noticed it. fixed and pushed it in master. 

need to check why git clone also fails. might be the repo has commit logs which are quite heavy.

you can either download the master repo to get the fix or just uncomment the package references and comment the project references as in this commit. 

https://github.com/skclusive/Skclusive.Blazor.Samples/commit/0650bdbf0913622ce128acd5a08d0945f994f0bb

**Comment by FieldMarshallVague** [comment]
Thank you!  I'll take a look.

**Comment by FieldMarshallVague** [comment]
Yep, that's working fine for me now, just unzipped into folder, opened solution and ran fine.  Thanks for sorting it out 👍
