### ISSUE TITLE
How access SidebarContent Burger Icon Anchor

### ISSUE THREAD

**Issue by kevinvenclovas** [skclusive/Skclusive.Blazor.Samples#15]
How can i set the sidebar burger icon to the left side in the dashboard sample?

**Comment by skclusive** [comment]
it is not configurable now. but can be added. it is from here https://github.com/skclusive/Skclusive.Material.Layout/blob/master/src/Topbar/Topbar.razor#L31

if urgent, you can clone and build the project locally and replace the package reference (Skclusive.Material.Layout) to your local project or package.
