### ISSUE TITLE
How to configure the Server to listen all IPs?

### ISSUE THREAD

**Issue by Oleg26Dev** [skclusive/Skclusive.Blazor.Samples#5]
I build a Blazor Server, run it on machine but it responds on localhost only, i.e. http://localhost:5000 but does not respond when I query it from an exrternal host http://myhostIP:5000 This myhostIP pinged ok. FW is off. In VS2019 in the project settings: App URL: https://localhost:5001;http://localhost:5000

How to configure Blazor Server to listen (all) hosts IP addresses using appsetings.json without hardcoding?

**Comment by skclusive** [comment]
I guess that might be due to the limitation of development server in VS2019. Recently i had published similar app to Azure without code or port changes.

**Comment by skclusive** [comment]
closing it. let me know if you need more details.
